### PR TITLE
Finished with website numbering

### PR DESCRIPTION
**Pull request by SamCain04**
should have completed all the numbering for new ticket and created the architecture for going to different tickets.

### CODE REVIEW

**Review by hannahpenado — CHANGES_REQUESTED** [review]
Just remove these files and we can merge:
ssts/__init__.py
ssts/templates/new/ticket.html

**Comment by SamCain04** [comment]
Could someone help me out with the changes, I don't quite understand how to resolve conflicts

**Review by hannahpenado — APPROVED** [review]

**Comment by hannahpenado** [comment]
Try updating your main branch by going to your repository, you should be able to update your main branch in your forked repository, then do another pull request to the same branch and I think it should update the files that conflict, it's usually because some files aren't up to date

**Comment by dallonjarman** [comment]
If you click on resolve conflicts and delete everything inside the file and paste in the code you are trying to submit and commit those changes it will resolve the conflict

**Pull request merged**
