### PR TITLE
finished the requested updates to init.py and wrote some sudo for tic…

### PR DESCRIPTION
**Pull request by SamCain04**
I apologize for the late request. I am not very competent in github yet and was waiting till i was sure I wouldn't mess up the branch

### CODE REVIEW

**Comment by SamCain04** [comment]
fulfills request #2

**Review by dallonjarman — APPROVED** [review]
Looks great! I appreciate all the comments! I don't see any issues with this. I'm going to submit my approval

**Comment by cmd644** [comment]
Fixed some of the syntactic issues, removed the page that would cause many HTML pages to be created. Will wait on one other person to review before merging.

**Comment by cmd644** [comment]
Merging to be able to continue development work.

**Pull request merged**
