### PR TITLE
D3

### PR DESCRIPTION
**Pull request by dallonjarman**
Adding D3 to main.

Edited D2 as well to make it look more clean.

### CODE REVIEW

**Comment by oliveoil222** [comment]
Swag money, this looks good!

**Comment by dallonjarman** [comment]
Sorry for the million and a half commit changes. Only wanted to add D3 to main. 
Resolves #70. 
Once approved pull request in the files changed tab, make sure to add issue#

**Comment by dallonjarman** [comment]
If any issues appear please let me know, I will change them asap

**Review by oliveoil222 — APPROVED** [review]

**Review by cmd644 — APPROVED** [review]
Looks great! Should be good!

**Comment by hannahpenado** [comment]
Looks good to me!

**Review by hannahpenado — APPROVED** [review]

**Comment by dallonjarman** [comment]
Dallon Jarman (14%) - Converted the D2 to Markdown
Olivia Vester (20%) - Created the System Description
Hannah Penado (20%) - Helped create the UML Model
Sam Cain (18%) - Helped write and format the description
Charles Descamps (14%) - Helped create the UML Model
Jared Kaige (14%) - Helped create the UML Model

**Review by SamCain04 — COMMENTED** [review]
all looks good

**Review by jjkagie — APPROVED** [review]
Looks good.

**Pull request closed without merging**
