### PR TITLE
Hannah db branch

### PR DESCRIPTION
**Pull request by hannahpenado**
Updated the collection functions to add info and changed the file to be addInfo since it's a more descriptive title of what the file's functions do. Verified the databases connect to mongodb and make changes when the functions are called. The uri variable doesn't include the password, just has some brackets for where the password should be inputted if you want to run any tests.

### CODE REVIEW

**Comment by SamCain04** [comment]
looks good to me

**Review by cmd644 — CHANGES_REQUESTED** [review]
Other than the .DS_Store files, this looks really good! Once the .DS_Store files are gone, we will merge and test.

**Review by dallonjarman — APPROVED** [review]
Looks amazing! I don't see anything that needs changing

**Review by SamCain04 — COMMENTED** [review]
I see no issues here

**Pull request merged**
