### PR TITLE
Adding D2

### PR DESCRIPTION
**Pull request by dallonjarman**
Olivia: 16%
Hannah: 16%
Sam: 16%
Charles: 16%
Dallon: 16%
Jared: 16%

All sections were collaborated on by all group members

### CODE REVIEW

**Comment by oliveoil222** [comment]
Looks good!

**Comment by SamCain04** [comment]
this looks good to me

**Comment by dallonjarman** [comment]
Updated pull request

**Comment by jjkagie** [comment]
Looks good

**Pull request merged**
