### PR TITLE
Adding the D3 Class Diagram 

### PR DESCRIPTION
**Pull request by hannahpenado**
Adding the D3 Class Diagram Rough draft with .md file rough draft, might need to take out the Sign In class since it could be part of either the user class or the database class. I'll be editing this pull request to just include the md file and png for the class diagram.

### CODE REVIEW

**Review by hannahpenado — COMMENTED** [review]
These are the files to approve for the pull request, just from this commit

**Review by oliveoil222 — APPROVED** [review]
Looks great!

**Review by cmd644 — APPROVED** [review]
Class Diagram looks good!

**Review by dallonjarman — APPROVED** [review]
Looks amazing1

**Pull request merged**
